R2Northstar/NorthstarTF

redirects.json

ModdingDocs are referenced in top bar but redirect gives 404

Add redirect for modding docs

---

dist/index.html

FlightCore generally works better for end users, as well as being actively updated and maintained. Viper is still a good mod manager, and I think it should stay as an option (unless somehow we come to a conclusion and one centralized launcher)
I don't mean to cause any controversy or ill will towards 0negal with this change, and hope that it won't happen

Change order of installers to FlightCore, VTOL, Viper, Manual on Northstar.tf

---

dist/index.html

This is needed to verify the link to `northstar.tf` on the [Northstar Fosstodon account](https://fosstodon.org/@R2Northstar).
The tag is purposefully inside the head of the page as I don't know whether we want to (visually) link to the account from the website yet.

Link to Mastodon profile for verification

---

dist/data/contrib.json
dist/data/core.json
dist/data/past-contrib.json
dist/script/credits.js

This PR loads the credits for various categories (`core`, `contrib`, `past-contrib`) from JSON files instead of hardcoding the values in JS.
The reason being that I'm planning to add another category called `community`.
With the move to JSON I can add a [scheduled GitHub Actions feature](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) that pulls all the contributors from all repositories and then commits the resulting JSON file.
This means we can get a regularly updated list of all contributors shown on the website :eyes:
Rendered result:
(They should look the same)
Before this PR  |  This PR:
:-------------------------:|:-------------------------:

Load credits from JSON files

---

dist/script/credits.js

So they only get loaded when scrolled to.

Lazy load GitHub profile pictures

---

dist/index.html

Preloads the installer JSON so that it isn't held up by slow networks

Preload installers JSON

---

dist/credits/index.html
dist/index.html
dist/servers/index.html

When the site was first made, the alt text for the GitHub icon was incorrectly set to "Modding Documentation".
Since then it continued to get copy-pasted to other subpages without anyone ever noticing.

Fix alt text for GitHub icon

---

dist/data/installers.json
dist/index.html
dist/installers/index.html
dist/script/installers.js
dist/style/header.css
dist/style/installers.css

Add a subpage listing all installers. This can in the future be extended to showcase more community made creations.
This is a continuation of #50 with some additional things fixed that I missed when additionally reviewing #50, updated with recent changes in main introduced by #52 and related PRs as well as no changes to which installers are considered featured for now.
As the majority of logic comes from #50 I made sure to co-author accordingly for appropriate contribution credit.

Add installers subpage

---

dist/installers/index.html

Installers subpage has its own CSS file instead of the main one

Load correct CSS for installers page

---

dist/data/installers.json

Given that Viper now supports launching on Linux since [`1.12.0`](https://github.com/0neGal/viper/releases/tag/v1.12.0) release I think it's appropriate to re-instate the tag showing Linux support.

Re-add Linux tag for Viper

---

dist/roadmap/index.html

There were a few leftover copy/pasted changes in #68 when it was merged.
This PR removes those.

Fix copy pasted leftovers on roadmap page

---

.github/workflows/deploy.yaml

Renders the webpage using astro and deploys it to `deploy` branch so that Atlas/masterserver can then pull from it.

Add GitHub Actions workflow to deploy rendered page to branch

---

src/data/contributors.ts

Remove manual line break in rexx' description as it gets escaped with astro rewrite and is not necessary with proper spacing anyway
Before:
After:

Remove manual line break in rexx' description

---

src/data/installers.ts

This IMO might be a controversial change given that I wrote FlightCore but there has a been a common sentiment over the last few months that out of FlightCore, VTOL, and Viper, FlightCore is the installer/mod-manager that causes the least issues with end-users.
It's not without reason that #48 exists. Further showing 4 different installation options confuses end-usersbased on feedback on Discord and it makes sense to highlight a mod-manager that is developed by someone closely associated with Northstar development.
At the same time I'm well aware of the improvements @0neGal made to Viper in the last few weeks and that VTOL also still sees development whenever @BigSpice is able to work on it.
So I struggle whether to merge this change or not and would highly appreciate any feedback on this …

Move Viper and VTOL to collapsed section

---

src/components/CommunityContributors.astro
src/data/community-contributors.ts
src/pages/credits.astro

This section will be populated by everyone not manually mentioned that has contributed to the project according to GitHub API
Spliced from #45
Successor of #46

Add section for community contributors

---

scripts/scrape-for-contributors.py

Otherwise it gets added to the list as well as it tried via 5dfe7f16ac54a0b11651ae65fa0ba23d66bdf144

Ignore GitHub Actions bot for community contributor list

---

src/data/contributors.ts

Moves myself to core contributors and add MAD to personal contributions, as suggested in https://github.com/R2Northstar/NorthstarTF/pull/88.

Move Alystrasz to core contributor

---

scripts/scrape-for-contributors.py

Adds 0neGal/viper as one of the none-org repos that we collect community contributors from to display on our [credits page](https://northstar.tf/credits/).

Collect community contributors from Viper

---

.github/workflows/periodic-scrape.yaml
scripts/scrape-for-contributors.py

Add option to pass GitHub token via CLI arg and make use of it in CI
Taken from #98

Add option to pass GitHub token via CLI arg

---

src/data/contributors.ts

Add "Docs" as one of the areas in Gecko's description on credits page.

Mention docs in Gecko's description

---

src/pages/credits.astro

Adds an id attribute to the container to be able to directly link to the section via `/credits/#reviewer-scoreboard`

Add id attribute for direct linking to section
