script/credits.js

The changes in this PR include 
- Changing the blurb for myself 
- Changing the name and blurb for snnag as requested in the contributor channel

Updated Credits

---

credits/index.html
index.html
script/servers.js
servers/index.html
style/header.css
style/servers.css

A direct port of https://cpdt.dev/northstar/ with some changes to fit in with the Northstar.tf header and footer design. Luckily the colour scheme is the same (thanks Barnaby!).

Add server browser

---

dist/script/servers.js
dist/servers/index.html
dist/style/servers.css

- Adds a column for region from server JSON
- Uses region in JSON for the "regions" picker on the left instead of parsing regions from server names
- Small quality of life change, made the "mods" picker use `or` instead of `and` logic (so picking multiple mods shows servers with any of those selected, instead of all of them like before)
Closes #9

Add regions to server browser

---

dist/credits/index.html
dist/style/credits.css

Add attribution notice for IP2Location

---

dist/servers/index.html

Add link to blog

---

dist/credits/index.html
dist/index.html

Only did `/servers` before, whoops

Add the link to blog to the remaining subpages

---

dist/script/servers.js

Add Frontier War to Server Browser

---

dist/index.html

Finally adds FlightCore to the list of installers.
Rendered

Add FlightCore to list of installers

---

dist/index.html

First time making a pr here, hopefully did it right. This link has been broken for a while now and finally got around to fixing it.

Fix broken VTOL Portable link

---

dist/script/credits.js

Adds VoyageDB for their multiple contributions: https://github.com/R2Northstar/NorthstarMods/commits?author=DBmaoha

Add VoyageDB to contributor list

---

dist/script/credits.js

Mention FlightCore and replace "moderator" with "maintainer"

Update Gecko's contributor description

---

dist/index.html

Console logs with trying to load `font-awesome` resource:

Remove dead font-awesome link

---

dist/script/credits.js

Idk, i got Navmeshes and Frontier defense stuff, is alright?

Add Zanieon to credits list

---

dist/credits/index.html

To better reflect the list of people under it

Update section headers

---

dist/credits/index.html
dist/script/credits.js

This section is for showing the list of people that contributed to Northstar in the past but are no longer actively working on Northstar
Rendered:

Add section for past contributors

---

dist/script/credits.js

https://github.com/R2Northstar/NorthstarLauncher/commits?author=Jan200101

Add Jan200101 to contributor list

---

dist/script/credits.js

https://github.com/R2Northstar/NorthstarMods/commits?author=EM4Volts
https://github.com/R2Northstar/ModdingDocs/commits?author=EM4Volts

Add 4V to contributor list

---

dist/script/credits.js

Surely i'll actually finish persistence at some point (rip pdiff 2022-2022)

Move spoon to core + update description

---

dist/script/credits.js

They are no longer active in Northstar to my knowledge

Move warmist to past contributors

---

dist/credits/index.html

Add a line to credits page that explains how to make changes to it. This is done to avoid cases of "why didn't you add me to the credits page" by highlighting that they can just request themselves to get added.
Rendered:

Add line how to make changes to credits page

---

dist/data/installers.json
dist/index.html
dist/script/installers.js
dist/style/common.css

Generate list of installers from JSON and use tags to describe capabilities. Allows for easier extending later.
Basically #50 without the installers subpage so that we an merge some stuff faster ^^
Rendered:

Generate list of installers from JSON

---

dist/script/index.js
dist/style/header.css

Check scroll on resize and use class so it doesn't interfere with the open menu

Improve header background logic

---

dist/style/index.css

- Prevents the scroll down thing getting cut off
- Properly centres on screens that are weird sizes

Centre the hero content properly

---

dist/style/index.css

> Changes some stuff with spacing to make it more readable and _pretty_ ✨

Improve layout of launchers section

---

dist/data/contrib.json
dist/data/core.json
dist/data/past-contrib.json

To improve credits load speed.

Use 128x128 size for GitHub avatars

---

dist/index.html

Preload Titanfall font

---

dist/404.html
dist/style/404.css
dist/style/index.css

Works on much smaller screens than it did before

Fix 404 page for smaller screens

---

dist/assets/scroll_down.svg
dist/index.html
dist/style/index.css

should very closely match how it looked before but fixes issues on mobile

Use SVG icon for scroll down indicator

---

dist/servers/index.html

Add missing link to installers page from server list page
Was forgotten in #66, whoops.

Add missing link to installers page

---

dist/index.html
dist/installers/index.html
dist/roadmap/index.html
dist/servers/index.html
dist/style/header.css

A feedback I recently got was that Northstar is a bit directionless as it's not clear what's planned.
And while currently most new features and changes are based on the motivation of contributors, there are some greater goals that are somewhat known internally but might not be clear publicly as they are never communicated.
As such we should better communicate at least a big picture roadmap to give an idea of what we are working on in the long run.

Add initial roadmap page

---

README.MD

Not super satisfied with them but better than nothing :P

Add instructions for building webpage locally

---

.github/workflows/periodic-scrape.yaml

Add an Action to periodically scrape GitHub API for community contributors and PR any changes

Add Action to periodically generate list of community contributors

---

src/data/contributors.ts

@GeckoEidechse Giving me hopes this PR will make to it, since i have done much more now than just Frontier Defense and Navmeshes as contributions to the project, such as making the match Challenges work again for Progression, rework the Intro Dropship and finally unfuck the Spawn system.

Move Zanieon to core contributors

---

src/data/contributors.ts

Spoken with @RoyalBlue1 in discord vc, asked her to properly update her development field for the project.

Update RoyalBlue's description

---

scripts/scrape-for-contributors.py

Collect scraped repos first before checking them for contributors.
This way we can easily extend the list for individual repos outside of Northstar orgs that are still valuable to the project.

refactor: Collect scraped repos first

---

public/redirects.json
src/components/Footer.astro
src/pages/index.astro
src/pages/servers.astro

Update links to ModdingDocs to new mkdocs version

Update links to ModdingDocs

---

public/redirects.json
src/data/installers.ts

Update links to Wiki to new mkdocs version

Update links to Wiki

---

src/pages/index.astro

Add id attributes to index page elements to allow linking to them

Add id attributes to index page elements

---

.github/workflows/periodic-scrape-reviews.yaml
.github/workflows/periodic-scrape.yaml
src/data/community-contributors.ts

There is a chance that branch protection rules will ruin this, but it [worked on my fork](https://github.com/ASpoonPlaysGames/NorthstarTF/actions/runs/12340598381)

Commit directly instead of making a PR in the scraping actions

---

src/components/Community.astro
src/data/community-videos.ts
src/pages/index.astro

Showcase trailers made for Northstar on the main web page
Rendered:
Closes #100

feat: Showcase community trailers on webpage

---

src/components/Community.astro

Cluster the different trailers by year based on the date manually added to each entry

feat: Cluster trailers by year
